"""Auto-generated clean tool library for the smol-mcp server. DO NOT EDIT BY HAND.

Generated by assemble_tools_lib.py from
MyGsearchSmolAgentsZ0WEM_OpAI_SWI_V04_i_SA_s_n_GA_BO_Gv16.py (read-only).
Contains only the Phase-1 smolagents Tool classes, the helper classes/functions
and constants they reference, and the imports they use. All top-level side
effects (network, headless Chrome, matplotlib.use, logging setup, agent/gradio
wiring) are excluded.
"""
from __future__ import annotations
import logging

logger = logging.getLogger("smol_mcp.tools")

import re
import httpx
import io
import csv
from smolagents.tools import Tool
import os
import json
import logging
import shutil
import pymupdf4llm
import fitz
from pdf2image import convert_from_path
import pytesseract
from multiprocessing import Pool
import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
import spacy
from functools import partial
import ast
import numpy as np
import math
from collections import deque

BULLETPROOF_FUNCTIONS = {
    "ackley": {
        "code": '''
import numpy as np

def objective(x):
    x_val, y_val = x[0], x[1]
    term1 = -20 * np.exp(-0.2 * np.sqrt(0.5 * (x_val**2 + y_val**2)))
    term2 = -np.exp(0.5 * (np.cos(2 * np.pi * x_val) + np.cos(2 * np.pi * y_val)))
    return term1 + term2 + 20 + np.e
''',
        "bounds": [[-32.768, 32.768], [-32.768, 32.768]],
        "global_min": 0.0
    },
    "ackley_mp": {
        "code": """
# MP version of function: ackley
import mpmath as mp

def objective(x):
    x_val = mp.mpf(x[0])
    y_val = mp.mpf(x[1])
    # Convert all constants to mpmath for full precision
    twenty = mp.mpf(20)
    point_two = mp.mpf(0.2)
    point_five = mp.mpf(0.5)
    two = mp.mpf(2)
    pi = mp.pi
    e = mp.e
    term1 = -twenty * mp.exp(-point_two * mp.sqrt(point_five * (x_val**2 + y_val**2)))
    term2 = -mp.exp(point_five * (mp.cos(two * pi * x_val) + mp.cos(two * pi * y_val)))
    return term1 + term2 + twenty + e
""",
        "bounds": '[[-32.768, 32.768], [-32.768, 32.768]]',
        "global_min": 0.0
    },
    "bukin n. 6": {
        "code": '''
import numpy as np

def objective(x):
    x_val, y_val = x[0], x[1]
    return 100 * np.sqrt(np.abs(y_val - 0.01 * x_val**2)) + 0.01 * np.abs(x_val + 10)
''',
        "bounds": [[-15, -5], [-3, 3]],
        "global_min": 0.0
    },
    "bukin n. 6_mp": {
        "code": """
# MP version of function: bukin n. 6
import mpmath as mp

def objective(x):
    x_val = mp.mpf(x[0])
    y_val = mp.mpf(x[1])
    # Convert all constants to mpmath for full precision
    hundred = mp.mpf(100)
    point_zero_one = mp.mpf(0.01)
    ten = mp.mpf(10)
    return hundred * mp.sqrt(mp.fabs(y_val - point_zero_one * x_val**2)) + point_zero_one * mp.fabs(x_val + ten)
""",
        "bounds": '[[-15, -5], [-3, 3]]',
        "global_min": 0.0
    },
    "cross-in-tray": {
        "code": '''
import numpy as np

def objective(x):
    x_val, y_val = x[0], x[1]
    inner = np.abs(np.sin(x_val) * np.sin(y_val) * np.exp(np.abs(100 - np.sqrt(x_val**2 + y_val**2) / np.pi))) + 1
    return -0.0001 * inner**0.1
''',
        "bounds": [[-10, 10], [-10, 10]],
        "global_min": -2.062611870822739
    },
    "cross-in-tray_mp": {
        "code": """
# MP version of function: cross-in-tray
import mpmath as mp

def objective(x):
    x_val = mp.mpf(x[0])
    y_val = mp.mpf(x[1])
    # Convert all constants to mpmath for full precision
    hundred = mp.mpf(100)
    pi = mp.pi
    point_zero_zero_zero_one = mp.mpf(0.0001)
    one = mp.mpf(1)
    inner = mp.fabs(mp.sin(x_val) * mp.sin(y_val) * mp.exp(mp.fabs(hundred - mp.sqrt(x_val**2 + y_val**2) / pi))) + one
    return -point_zero_zero_zero_one * inner**0.1
""",
        "bounds": '[[-10, 10], [-10, 10]]',
        "global_min": -2.062611870822739
    },
    "drop-wave": {
        "code": '''
import numpy as np

def objective(x):
    x_val, y_val = x[0], x[1]
    denom = 0.5 * (x_val**2 + y_val**2) + 2
    num = 1 + np.cos(12 * np.sqrt(x_val**2 + y_val**2))
    return -num / denom
''',
        "bounds": [[-5.12, 5.12], [-5.12, 5.12]],
        "global_min": -1.0
    },
    "drop-wave_mp": {
        "code": '''
import mpmath as mp
def objective(x):
    # mp.dps = dps
    x_val = mp.mpf(x[0])
    y_val = mp.mpf(x[1])
    # All constants converted to MP
    half = mp.mpf(0.5)
    twelve = mp.mpf(12)
    two = mp.mpf(2)
    one = mp.mpf(1)
    # Calculate denominator: 0.5*(x^2 + y^2) + 2
    denom = half * (x_val**2 + y_val**2) + two
    # Calculate numerator: 1 + cos(12 * sqrt(x^2 + y^2))
    num = one + mp.cos(twelve * mp.sqrt(x_val**2 + y_val**2))
    # Calculate result
    result = -num / denom
    return result''',
        "bounds": '[[-5.12, 5.12], [-5.12, 5.12]]',
        "global_min": -1.0
    },
    "eggholder": {
        "code": '''
import numpy as np

def objective(x):
    x_val, y_val = x[0], x[1]
    term1 = -(y_val + 47) * np.sin(np.sqrt(np.abs(x_val / 2 + y_val + 47)))
    term2 = -x_val * np.sin(np.sqrt(np.abs(x_val - (y_val + 47))))
    return term1 + term2
''',
        "bounds": [[-512, 512], [-512, 512]],
        "global_min": -959.6406627206158
    },
    "eggholder_mp": {
        "code": """
# MP version of function: eggholder
import mpmath as mp

def objective(x):
    x_val = mp.mpf(x[0])
    y_val = mp.mpf(x[1])
    # Convert all constants to mpmath for full precision
    forty_seven = mp.mpf(47)
    term1 = -(y_val + forty_seven) * mp.sin(mp.sqrt(mp.fabs(x_val / 2 + y_val + forty_seven)))
    term2 = -x_val * mp.sin(mp.sqrt(mp.fabs(x_val - (y_val + forty_seven))))
    return term1 + term2
""",
        "bounds": '[[-512, 512], [-512, 512]]',
        "global_min": -959.6406627206158
    },
    "gramacy & lee (2012)": {
        "code": '''
import numpy as np

def objective(x):
    x_val = x[0] if isinstance(x, list) or isinstance(x, np.ndarray) else x
    return np.sin(10 * np.pi * x_val) / (2 * x_val) + (x_val - 1)**4
''',
        "bounds": [[0.5, 2.5]],
        "global_min": -0.8690111349895001
    },
    "gramacy & lee (2012)_mp": {
        "code": """
# MP version of function: gramacy & lee (2012)
import mpmath as mp

def objective(x):
    x_val = mp.mpf(x[0])
    # Convert all constants to mpmath for full precision
    ten = mp.mpf(10)
    pi = mp.pi
    two = mp.mpf(2)
    one = mp.mpf(1)
    four = mp.mpf(4)
    term1 = mp.sin(ten * pi * x_val) / (two * x_val)
    term2 = (x_val - one)**four
    return term1 + term2
""",
        "bounds": '[["0.5", "2.5"]]',
        "global_min": -0.8690111349895001
    },
    "griewank": {
        "code": '''
import numpy as np

def objective(x):
    x_val, y_val = x[0], x[1]
    sum_sq = (x_val**2 + y_val**2) / 4000
    prod_cos = np.cos(x_val / np.sqrt(1)) * np.cos(y_val / np.sqrt(2))
    return sum_sq - prod_cos + 1
''',
        "bounds": [[-600, 600], [-600, 600]],
        "global_min": 0.0
    },
    "griewank_mp": {
        "code": """
# MP version of function: griewank
import mpmath as mp

def objective(x):
    x_val = mp.mpf(x[0])
    y_val = mp.mpf(x[1])
    # Convert all constants to mpmath for full precision
    four_thousand = mp.mpf(4000)
    one = mp.mpf(1)
    two = mp.mpf(2)
    one_point = mp.mpf(1)
    term1 = (x_val**2 + y_val**2) / four_thousand
    term2 = mp.cos(x_val / mp.sqrt(one)) * mp.cos(y_val / mp.sqrt(two))
    return term1 - term2 + one_point
""",
        "bounds": '[[-600, 600], [-600, 600]]',
        "global_min": 0.0
    },
    "holder table": {
        "code": '''
import numpy as np

def objective(x):
    x_val, y_val = x[0], x[1]
    inner = np.abs(1 - np.sqrt(x_val**2 + y_val**2) / np.pi)
    return -np.abs(np.sin(x_val) * np.cos(y_val) * np.exp(inner))
''',
        "bounds": [[-10, 10], [-10, 10]],
        "global_min": -19.20850256788675
    },
    "holder table_mp": {
        "code": """
# MP version of function: holder table
import mpmath as mp

def objective(x):
    x_val = mp.mpf(x[0])
    y_val = mp.mpf(x[1])
    # Convert all constants to mpmath for full precision
    one = mp.mpf(1)
    pi = mp.pi
    # sin = mp.sin
    # cos = mp.cos
    # exp = mp.exp
    inner = mp.fabs(one - mp.sqrt(x_val**2 + y_val**2) / pi)
    return -mp.fabs(mp.sin(x_val) * mp.cos(y_val) * mp.exp(inner))
""",
        "bounds": '[[-10, 10], [-10, 10]]',
        "global_min": -19.20850256788675
    },
    "langermann": {
        "code": '''
import numpy as np

def objective(x):
    a = [3, 5, 2, 1, 7]
    b = [5, 2, 1, 4, 9]
    c = [1, 2, 5, 2, 3]
    x_val, y_val = x[0], x[1]
    total = 0.0
    for i in range(len(a)):
        d2 = (x_val - a[i])**2 + (y_val - b[i])**2
        term = np.exp(-d2 / np.pi) * np.cos(np.pi * d2)
        total += c[i] * term
    return -total
''',
        "bounds": [[0, 10], [0, 10]],
        "global_min": -5.147
    },
    "langermann_mp": {
        "code": '''
def objective(x):
    a = [3, 5, 2, 1, 7]
    b = [5, 2, 1, 4, 9]
    c = [1, 2, 5, 2, 3]
    x_val, y_val = mp.mpf(x[0]), mp.mpf(x[1])
    total = mp.mpf(0.0)
    for i in range(len(a)):
        d2 = (x_val - mp.mpf(a[i]))**2 + (y_val - mp.mpf(b[i]))**2
        term = mp.exp(-d2 / mp.pi) * mp.cos(mp.pi * d2)
        total += mp.mpf(c[i]) * term
    return -total
''',
        "bounds": '[[0, 10], [0, 10]]',
        "global_min": -5.147
    },
    "levy": {
        "code": '''
import numpy as np

def objective(x):
    x_val, y_val = x[0], x[1]
    w_x = 1 + (x_val - 1) / 4
    w_y = 1 + (y_val - 1) / 4
    term1 = np.sin(np.pi * w_x)**2
    term2 = (w_x - 1)**2 * (1 + 10 * np.sin(np.pi * w_x + 1)**2)
    term3 = (w_y - 1)**2 * (1 + np.sin(2 * np.pi * w_y)**2)
    return term1 + term2 + term3
''',
        "bounds": [[-10, 10], [-10, 10]],
        "global_min": 0.0
    },
    "levy_mp": {
        "code": """
# MP version of function: levy
import mpmath as mp

def objective(x):
    x_val = mp.mpf(x[0])
    y_val = mp.mpf(x[1])
    # Convert all constants to mpmath for full precision
    one = mp.mpf(1)
    four = mp.mpf(4)
    pi = mp.pi
    ten = mp.mpf(10)
    two = mp.mpf(2)
    w_x = one + (x_val - one) / four
    w_y = one + (y_val - one) / four
    term1 = mp.sin(pi * w_x)**2
    term2 = (w_x - one)**2 * (one + ten * mp.sin(pi * w_x + one)**2)
    term3 = (w_y - one)**2 * (one + mp.sin(two * pi * w_y)**2)
    return term1 + term2 + term3
""",
        "bounds": '[[-10, 10], [-10, 10]]',
        "global_min": 0.0
    },
    "levy n. 13": {
        "code": '''
import numpy as np

def objective(x):
    x_val, y_val = x[0], x[1]
    term1 = np.sin(3 * np.pi * x_val)**2
    term2 = (x_val - 1)**2 * (1 + np.sin(3 * np.pi * y_val)**2)
    term3 = (y_val - 1)**2 * (1 + np.sin(2 * np.pi * y_val)**2)
    return term1 + term2 + term3
''',
        "bounds": [[-10, 10], [-10, 10]],
        "global_min": 0.0
    },
    "levy n. 13_mp": {
        "code": """
# MP version of function: levy n. 13
import mpmath as mp

def objective(x):
    x_val = mp.mpf(x[0])
    y_val = mp.mpf(x[1])
    # Convert all constants to mpmath for full precision
    three = mp.mpf(3)
    pi = mp.pi
    one = mp.mpf(1)
    two = mp.mpf(2)
    term1 = mp.sin(three * pi * x_val)**2
    term2 = (x_val - one)**2 * (one + mp.sin(three * pi * y_val)**2)
    term3 = (y_val - one)**2 * (one + mp.sin(two * pi * y_val)**2)
    return term1 + term2 + term3
""",
        "bounds": '[[-10, 10], [-10, 10]]',
        "global_min": 0.0
    },
    "rastrigin": {
        "code": '''
import numpy as np

def objective(x):
    x_val, y_val = x[0], x[1]
    return 20 + x_val**2 + y_val**2 - 10 * (np.cos(2 * np.pi * x_val) + np.cos(2 * np.pi * y_val))
''',
        "bounds": [[-5.12, 5.12], [-5.12, 5.12]],
        "global_min": 0.0
    },
    "rastrigin_mp": {
        "code": """
# MP version of function: rastrigin
import mpmath as mp

def objective(x):
    x_val = mp.mpf(x[0])
    y_val = mp.mpf(x[1])
    # Convert all constants to mpmath for full precision
    twenty = mp.mpf(20)
    two = mp.mpf(2)
    pi = mp.pi
    ten = mp.mpf(10)
    term1 = twenty + x_val**2 + y_val**2
    term2 = ten * (mp.cos(two * pi * x_val) + mp.cos(two * pi * y_val))
    return term1 - term2
""",
        "bounds": '[[-5.12, 5.12], [-5.12, 5.12]]',
        "global_min": 0.0
    },
    "schaffer n. 2": {
        "code": '''
import numpy as np

def objective(x):
    x_val, y_val = x[0], x[1]
    num = np.sin(np.sqrt(x_val**2 + y_val**2))**2 - 0.5
    denom = (1 + 0.001 * (x_val**2 + y_val**2))**2
    return 0.5 + num / denom
''',
        "bounds": [[-100, 100], [-100, 100]],
        "global_min": 0.0
    },
    "schaffer n. 2_mp": {
        "code": """
# MP version of function: schaffer n. 2
import mpmath as mp

def objective(x):
    x_val = mp.mpf(x[0])
    y_val = mp.mpf(x[1])
    # Convert all constants to mpmath for full precision
    zero_point_zero_zero_one = mp.mpf(0.001)
    one = mp.mpf(1)
    two = mp.mpf(2)
    zero_point_five = mp.mpf(0.5)
    half = mp.mpf(0.5)
    num = mp.sin(mp.sqrt(x_val**2 + y_val**2))**2 - zero_point_five
    denom = (one + zero_point_zero_zero_one * (x_val**2 + y_val**2))**two
    return half + num / denom
""",
        "bounds": '[[-100, 100], [-100, 100]]',
        "global_min": 0.0
    },
    "schaffer n. 4": {
        "code": '''
import numpy as np

def objective(x):
    x_val, y_val = x[0], x[1]
    num = np.cos(np.sin(np.abs(x_val**2 - y_val**2)))**2 - 0.5
    denom = (1 + 0.001 * (x_val**2 + y_val**2))**2
    return 0.5 + num / denom
''',
        "bounds": [[-100, 100], [-100, 100]],
        "global_min": 0.292579
    },
    "schaffer n. 4_mp": {
        "code": """
# MP version of function: schaffer n. 4
import mpmath as mp

def objective(x):
    x_val = mp.mpf(x[0])
    y_val = mp.mpf(x[1])
    # Convert all constants to mpmath for full precision
    zero_point_zero_zero_one = mp.mpf(0.001)
    one = mp.mpf(1)
    two = mp.mpf(2)
    zero_point_five = mp.mpf(0.5)
    half = mp.mpf(0.5)
    num = mp.cos(mp.sin(mp.fabs(x_val**2 - y_val**2)))**2 - zero_point_five
    denom = (one + zero_point_zero_zero_one * (x_val**2 + y_val**2))**two
    return half + num / denom
""",
        "bounds": '[[-100, 100], [-100, 100]]',
        "global_min": 0.292579
    },
    "schwefel": {
        "code": '''
import numpy as np

def objective(x):
    x_val, y_val = x[0], x[1]
    return 837.9658 - x_val * np.sin(np.sqrt(np.abs(x_val))) - y_val * np.sin(np.sqrt(np.abs(y_val)))
''',
        "bounds": [[-500, 500], [-500, 500]],
        "global_min": 0.0
    },
    "schwefel_mp": {
        "code": """
# MP version of function: schwefel
import mpmath as mp

def objective(x):
    x_val = mp.mpf(x[0])
    y_val = mp.mpf(x[1])
    # Convert all constants to mpmath for full precision
    eight_hundred_thirty_seven_point_nine_six_five_eight = mp.mpf(837.9658)
    # sin = mp.sin
    # sqrt = mp.sqrt
    # fabs = mp.fabs
    return eight_hundred_thirty_seven_point_nine_six_five_eight - x_val * mp.sin(mp.sqrt(mp.fabs(x_val))) - y_val * mp.sin(mp.sqrt(mp.fabs(y_val)))
""",
        "bounds": '[[-500, 500], [-500, 500]]',
        "global_min": 0.0
    },
    "shubert": {
        "code": '''
import numpy as np

def objective(x):
    x_val, y_val = x[0], x[1]
    sum_x = sum(i * np.cos((i + 1) * x_val + i) for i in range(1, 6))
    sum_y = sum(i * np.cos((i + 1) * y_val + i) for i in range(1, 6))
    return sum_x * sum_y
''',
        "bounds": [[-10, 10], [-10, 10]],
        "global_min": -186.73090883102395
    },
    "shubert_mp": {
        "code": '''
import mpmath as mp

def objective(x):
    # Convert inputs to mpmath types
    x_val = mp.mpf(x[0])
    y_val = mp.mpf(x[1])
    # Convert integers to mpf for full precision
    sum_x = mp.mpf(0)
    for i in range(1, 6):
        i_mp = mp.mpf(i)
        sum_x += i_mp * mp.cos((i_mp + 1) * x_val + i_mp)
    sum_y = mp.mpf(0)
    for i in range(1, 6):
        i_mp = mp.mpf(i)
        sum_y += i_mp * mp.cos((i_mp + 1) * y_val + i_mp)
    return sum_x * sum_y
''',
        "bounds": '[[-10, 10], [-10, 10]]',
        "global_min": -186.73090883102395
    },
    "mogadish": {
        "code": """
import numpy as np

def objective(x):
    # M.O.G.A. Dish (Make Optimizers Global Again)
    # A macroscopic soup dish with microscopic Littlewood-Paley oscillations.
    # Global Minimum is approx 1.28 near [0,0], but the floor is noisy.

    x_val, y_val = x[0], x[1]
    r = np.sqrt(x_val**2 + y_val**2 + 1e-12)
    theta = np.arctan2(y_val, x_val)

    # 1. Mean Bowl (The Dish)
    # A quartic-quadratic mix to create a nice rim and a flat-ish bottom
    z_base = 1.25 + 0.18*r**2 - 0.012*r**4 + 0.08*np.sin(np.pi*r/5) + 0.03*np.cos(6*np.pi*r/5)

    # 2. Littlewood-Paley style micro-oscillations
    # We use a local RNG based on theta to create 'angular chaos' without breaking global state
    perturb = 0.0

    # Deterministic chaos seed based on angle (sectors of roughness)
    seed_val = int(42 + (1000 * abs(theta)) % 137)
    rng = np.random.default_rng(seed_val)

    # Sum of dyadic bands
    for j in range(3, 15): # Range adjusted to be 'visible' to standard float64 optimizers
        freq = 2**j
        # Amplitude decays, but creates a 'Weierstrass function' texture
        amp = 1e-3 * 2**(-0.5*j)

        phase_shift = 3.0 * np.sin(0.7*theta)
        coeff_mod = np.cos(1.3*theta + 0.1*j)

        perturb += amp * coeff_mod * np.sin(freq * r + phase_shift)

    return z_base + perturb
    """,
        "bounds": [(-4.0, 4.0), (-4.0, 4.0)],
        "global_min": 1.28  # Approximate, due to chaotic floor
    },
    "mogadish_mp": {
        "code": """
import mpmath as mp

def objective(x):
    # MOGAdish High-Precision
    # Note: 'mp' is pre-injected by the tool

    x_val = x[0]
    y_val = x[1]

    # Planck-scale epsilon to prevent singularity at 0
    epsilon = mp.mpf('1e-35')

    r = mp.sqrt(x_val**2 + y_val**2 + epsilon)
    theta = mp.atan2(y_val, x_val)

    # 1. Mean Bowl (High Precision constants)
    z_base = (mp.mpf('1.25') +
              mp.mpf('0.18') * r**2 -
              mp.mpf('0.012') * r**4 +
              mp.mpf('0.08') * mp.sin(mp.pi * r / 5) +
              mp.mpf('0.03') * mp.cos(6 * mp.pi * r / 5))

    # 2. Micro-oscillations
    perturb = mp.mpf(0.0)

    # We simulate the chaos deterministically using mpmath functions
    # (Since we can't easily use numpy.random inside the MP scope without casting)

    # Sum of bands
    for j in range(3, 15):
        freq = mp.power(2, j)
        # Amplitude
        amp = mp.mpf('1e-3') * mp.power(2, -0.5 * j)

        # Phase logic using mp math
        phase_shift = 3.0 * mp.sin(0.7 * theta)
        coeff_mod = mp.cos(1.3 * theta + 0.1 * j)

        perturb += amp * coeff_mod * mp.sin(freq * r + phase_shift)

    return z_base + perturb
    """,
        "bounds": '[[-2.5, 2.5], [-2.5, 2.5]]',
        # "bounds": '[[-10, 10], [-10, 10]]',
        "global_min": 1.28  # Approximate, due to chaotic floor
    }
}

csv_field_delim = ';'

valid_url_pattern = r"^https?://.*"

class SafeOpenTool(Tool):
    name = "safe_open_tool"
    description = """This is a tool that opens a file replacing open().
                     It enforces security by forcing file access to occur strictly within the designated safe directory.
                     Any directory paths provided in 'file_name' will be stripped."""
    inputs = {
        "file_name": {
            "type": "string",
            "description": "The name of the file to be opened. directory components are ignored; the file is looked up in the safe directory."
        },
        "mode": {
            "type": "string",
            "description": "'rt' for text files, 'rb' for binary files (pdf, docx...)"
        }
    }
    output_type = "object"

    def __init__(self, safe_dir):
        super().__init__()
        self.safe_dir = safe_dir
        # logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
        # logging.info("Secure SafeOpenTool initialized.")
        logging.info(f"SafeOpenTool initialized.\n*** ✅ ---> Files will be saved in '{os.path.abspath(self.safe_dir)}'")

    def forward(self, file_name, mode):
        # 1. Sanitize: Ignore whatever path the agent provided and force usage of basename
        #    Example: 'uploads/run1.csv' -> 'run1.csv'
        #    Example: 'C:/Windows/System32/run1.csv' -> 'run1.csv'
        clean_name = os.path.basename(file_name)

        # 2. Construct the forced path inside the safe directory
        file_path = os.path.join(self.safe_dir, clean_name)
        abs_file_path = os.path.abspath(file_path)
        abs_safe_dir = os.path.abspath(self.safe_dir)

        # 3. Security Verification (Double check)
        #    Ensure the resulting path is actually inside the safe dir
        if not abs_file_path.startswith(abs_safe_dir):
            raise ValueError(f"Access denied: File path {abs_file_path} is outside the allowed path {abs_safe_dir}")
        # logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
        # logging.info(f"SavePlotTool initialized.\n*** ✅ ---> Plots will be saved in '{os.path.abspath(self.safe_dir)}'")
        logging.info(f"SafeOpenTool: Opening '{abs_file_path}' in mode '{mode}'")

        try:
            if 'b' in mode:
                return open(abs_file_path, mode)
            else:
                # Default to text mode with utf-8 encoding
                return open(abs_file_path, mode, encoding='utf-8')
        except FileNotFoundError:
            raise FileNotFoundError(f"File not found: {clean_name} (looked in {abs_safe_dir})")

class PDFSplitterToolGv2(SafeOpenTool):
    name = "pdf_splitter_tool"
    description = """Splits a PDF into Markdown files. It ensures chunks do not break
                     in the middle of a paragraph by splitting at double newlines."""
    inputs = {
        "file_name": {
            "type": "string",
            "description": "The pathname or URL of the PDF file to be split."
        },
        "pages_per_chunk": {
            "type": "integer",
            "description": "Maximum number of pages per generated Markdown file."
        }
    }
    output_type = "string"

    def __init__(self, safe_dir):
        super().__init__(safe_dir)
        logging.info("Secure PDFSplitterToolGv2 initialized.")

    def forward(self, file_name, pages_per_chunk):
        # 1. Handle Input (Logic mirrored from PDF2TXTTool)
        if os.path.isfile(file_name) or not re.match(valid_url_pattern, file_name):
            # SafeOpenTool handles path stripping and security logic
            binary_file = super().forward(file_name, "rb")
        elif re.match(valid_url_pattern, file_name) is not None:
            # Handle Web URL
            logging.info(f"PDFSplitterTool: Downloading PDF from {file_name}")
            with httpx.stream("GET", file_name) as response:
                binary_file = io.BytesIO(b"".join(response.iter_raw()))
        else:
            raise ValueError(f"The string {file_name} is neither a web URL nor a valid path.")

        try:
            doc = fitz.open(stream=binary_file.read(), filetype="pdf")
            total_pages = len(doc)
            clean_base = os.path.splitext(os.path.basename(file_name))[0]

            all_created_files = []
            chunk_count = 1

            # This buffer will hold the "hanging" paragraph text from the previous chunk
            carry_over_text = ""

            for start_page in range(0, total_pages, pages_per_chunk):
                end_page = min(start_page + pages_per_chunk, total_pages)
                page_range = list(range(start_page, end_page))

                # Extract current range
                current_md = pymupdf4llm.to_markdown(doc, pages=page_range)

                # Prepend any text that was cut off from the previous iteration
                full_text = carry_over_text + current_md

                # If this is not the last chunk, we find the last logical break
                if end_page < total_pages:
                    # Look for the last double newline (paragraph break)
                    last_break = full_text.rfind("\n\n")

                    if last_break != -1:
                        # Split: 'content' goes to file, 'carry_over' goes to next loop
                        content = full_text[:last_break].strip()
                        carry_over_text = full_text[last_break:].strip() + "\n\n"
                    else:
                        # If no double newline found, keep all and clear carry_over
                        content = full_text
                        carry_over_text = ""
                else:
                    # Last chunk: take everything remaining
                    content = full_text

                # Save the content
                out_name = f"{clean_base}_part{chunk_count}_p{start_page+1}-{end_page}.md"
                out_path = os.path.join(self.safe_dir, out_name)

                with open(out_path, "w", encoding="utf-8") as f:
                    f.write(content)

                all_created_files.append(out_name)
                chunk_count += 1

            doc.close()
            return f"Created {len(all_created_files)} semantic chunks: {', '.join(all_created_files)}"

        except Exception as e:
            return f"Error: {str(e)}"

class PDF2TXTTool(SafeOpenTool):
    name = "pdf_2_txt_tool"
    description = """This is a tool that extracts the text from a PDF file.
                     If the file is not in a safe directory it raises an exception."""
    inputs = {
        "file_name": {
            "type": "string",
            "description": "The pathname or URL of the PDF file to be opened."
        }
    }
    output_type = "string"

    def __init__(self, safe_dir):
        super().__init__(safe_dir)
        # logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
        logging.info("Secure PDF2TXTTool initialized.")

    def forward(self, file_name):
        if os.path.isfile(file_name):
            # if it's a path to a local file:
            # binary_file = super().forward(file_name, "rb") # invoke SafeOpenTool
            binary_file = super().forward(file_name, "rb")  # invoke SafeOpenTool
        elif re.match(valid_url_pattern, file_name) is not None:
            # else, if it's a web link:
            with httpx.stream("GET", file_name) as response:
                binary_file = io.BytesIO(b"".join(response.iter_raw()))
        else:
            raise ValueError(f"The string {file_name} is neither a web URL nor a path to a local file")

        # Iterate through all the pages and extract text
        text = ""
        import fitz
        with fitz.open("pdf", binary_file.read()) as pdf:
            # Iterate through all the pages and extract text
            for page_number in range(len(pdf)):
                page = pdf[page_number]
                page_text = page.get_text()  # Extract text from the current page
                # print(f"****** New page of {file_name}:\n{page_text}")
                text += page_text
        binary_file.close()
        return text

class PDFAnalyzerTool(Tool):
    name = "pdf_analyzer_tool"
    description = """Analyzes a PDF file to determine the best text extraction method (direct vs. OCR).
                     It provides a detailed report on text content, images, and text readability.
                     The file must be located in the secure upload directory."""
    inputs = {
        "pdf_filename": {
            "type": "string",
            "description": "The name of the PDF file (e.g., 'report.pdf') located in the safe upload directory."
        },
        "min_readable_ratio": {
            "type": "number",  # <-- FIX IS HERE
            "description": "The minimum ratio of readable characters (0.0 to 1.0) to consider text directly extractable. Defaults to 0.7.",
            "nullable": True
        },
        "sample_pages": {
            "type": "integer",
            "description": "The number of pages to sample for a quick analysis of large documents. Defaults to 3.",
            "nullable": True
        }
    }
    output_type = "string"

    def __init__(self, safe_dir: str):
        super().__init__()
        self.safe_dir = safe_dir
        if not os.path.isdir(self.safe_dir):
            os.makedirs(self.safe_dir, exist_ok=True)
        # logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
        logging.info("Secure PDFAnalyzerTool initialized.")

    def _sample_pages(self, total_pages, sample_pages_count):
        if total_pages <= sample_pages_count:
            return list(range(total_pages))
        step = total_pages / sample_pages_count
        return [int(i * step) for i in range(sample_pages_count)]

    def _calculate_readable_ratio(self, text):
        if not text:
            return 0.0
        readable_pattern = r'[a-zA-Z0-9\s\.,;:!?\-\'\"()\[\]{}/@#$%&*+=<>|~`]'
        readable_chars = len(re.findall(readable_pattern, text))
        total_chars = len(text)
        return readable_chars / total_chars if total_chars > 0 else 0.0

    def _recommend_method(self, results):
        has_text = results["has_text"]
        has_images = results["has_images"]
        is_readable = results["text_is_readable"]
        avg_readable = results["avg_readable_ratio"]

        if not has_text and has_images:
            return "OCR_REQUIRED", 0.95
        if not has_text and not has_images:
            return "EMPTY_OR_UNSUPPORTED", 0.95
        if has_text and is_readable:
            confidence = 0.95 if not has_images else 0.85
            return "DIRECT_EXTRACTION", confidence
        if has_text and not is_readable:
            if avg_readable < 0.3:
                return "OCR_REQUIRED", 0.90
            else:
                return "HYBRID", 0.70
        return "HYBRID", 0.50

    def _format_report(self, results):
        report_lines = []
        if "error" in results:
            report_lines.append("=" * 70)
            report_lines.append("PDF ANALYSIS ERROR")
            report_lines.append("=" * 70)
            report_lines.append(f"\nError: {results['error']}")
            if "path" in results:
                report_lines.append(f"Path: {results['path']}")
            report_lines.append("=" * 70)
            return "\n".join(report_lines)

        report_lines.append("=" * 70)
        report_lines.append("PDF TEXT EXTRACTION ANALYSIS REPORT")
        report_lines.append("=" * 70)
        report_lines.append("\nDocument Info:")
        report_lines.append(f"  Total Pages: {results['total_pages']}")
        report_lines.append(f"  Pages Sampled: {results['sampled_pages']}")
        report_lines.append("\nContent Detection:")
        report_lines.append(f"  Has Text Layer: {results['has_text']}")
        report_lines.append(f"  Has Images: {results['has_images']}")
        report_lines.append(f"  Text is Readable: {results['text_is_readable']}")
        report_lines.append(f"  Avg Readable Ratio: {results['avg_readable_ratio']:.2%}")

        report_lines.append("\nPer-Page Analysis:")
        for page in results['page_analysis']:
            report_lines.append(f"  Page {page['page_num']}:")
            report_lines.append(f"    Text Length: {page['text_length']} chars")
            report_lines.append(f"    Has Text: {page['has_text']}")
            report_lines.append(f"    Has Images: {page['has_images']}")
            report_lines.append(f"    Readable Ratio: {page['readable_ratio']:.2%}")

        report_lines.append("\n" + "=" * 70)
        report_lines.append(f"RECOMMENDATION: {results['recommended_method']}")
        report_lines.append(f"Confidence: {results['confidence']:.0%}")
        report_lines.append("=" * 70)

        method = results['recommended_method']
        report_lines.append("\nNext Steps:")
        if method == 'DIRECT_EXTRACTION':
            report_lines.append("  ✓ Use direct text extraction (e.g., pdf_2_txt_tool).")
        elif method == 'OCR_REQUIRED':
            report_lines.append("  ✓ Use OCR tools. Direct text extraction will likely fail.")
        elif method == 'HYBRID':
            report_lines.append("  ⚠ This PDF is mixed. Try direct extraction first, but be prepared to use OCR if results are poor.")
        else:
            report_lines.append("  ⚠ Document may be empty, corrupted, or use an unsupported format.")

        return "\n".join(report_lines)

    def forward(self, pdf_filename: str, min_readable_ratio: float = 0.7, sample_pages: int = 3):
        full_path = os.path.abspath(os.path.join(self.safe_dir, os.path.basename(pdf_filename)))
        safe_dir_abs = os.path.abspath(self.safe_dir)

        if not full_path.startswith(safe_dir_abs):
            return self._format_report({"error": f"Access denied. File '{pdf_filename}' is outside the safe directory.", "path": full_path})

        if not os.path.exists(full_path):
            return self._format_report({"error": "File not found", "path": full_path})

        try:
            doc = fitz.open(full_path)
        except Exception as e:
            return self._format_report({"error": f"Error opening PDF: {str(e)}", "path": full_path})

        total_pages = len(doc)
        if total_pages == 0:
            doc.close()
            return self._format_report({"error": "PDF document is empty (0 pages).", "path": full_path})

        page_indices = self._sample_pages(total_pages, sample_pages)

        results = {
            "total_pages": total_pages,
            "sampled_pages": len(page_indices),
            "has_text": False,
            "has_images": False,
            "text_is_readable": False,
            "avg_readable_ratio": 0.0,
            "page_analysis": [],
        }

        total_readable_ratio = 0.0
        for page_num in page_indices:
            page = doc.load_page(page_num)
            page_text = page.get_text()
            has_images = len(page.get_images(full=True)) > 0
            has_text = len(page_text.strip()) > 0

            results["has_text"] |= has_text
            results["has_images"] |= has_images

            readable_ratio = self._calculate_readable_ratio(page_text) if has_text else 0.0
            total_readable_ratio += readable_ratio

            results["page_analysis"].append({
                "page_num": page_num,
                "text_length": len(page_text),
                "has_text": has_text,
                "has_images": has_images,
                "readable_ratio": readable_ratio
            })

        doc.close()

        if len(page_indices) > 0:
            results["avg_readable_ratio"] = total_readable_ratio / len(page_indices)

        results["text_is_readable"] = results["avg_readable_ratio"] >= min_readable_ratio

        results["recommended_method"], results["confidence"] = self._recommend_method(results)

        return self._format_report(results)

class OCR2TXTTool(Tool):
    name = "ocr_2_txt_tool"
    description = """Extracts text from PDF files using Optical Character Recognition (OCR).
                     This tool is essential for scanned documents, PDFs containing only images, or when PDFAnalyzerTool recommends 'OCR_REQUIRED' or 'HYBRID'.
                     It is more resource-intensive than the standard pdf_2_txt_tool.
                     The file must be located in the secure upload directory."""
    inputs = {
        "file_name": {
            "type": "string",
            "description": "The name of the PDF file (e.g., 'scanned_report.pdf') located in the safe upload directory."
        },
        "language": {
            "type": "string",
            "description": "The language of the text in the document (e.g., 'eng' for English, 'ita' for Italian, 'fra' for French). Defaults to 'eng'.",
            "nullable": True
        }
    }
    output_type = "string"

    def __init__(self, safe_dir: str):
        super().__init__()
        self.safe_dir = os.path.abspath(safe_dir)
        if not os.path.isdir(self.safe_dir):
            os.makedirs(self.safe_dir, exist_ok=True)
        # logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
        logging.info("Secure OCR2TXTTool initialized.")

        # --- Proactive Dependency Check during Initialization ---
        tesseract_path = shutil.which('tesseract')
        if not tesseract_path:
            raise ImportError(
                "Tesseract is not installed or not in your PATH. "
                "OCR2TXTTool cannot function without it. "
                "Please install Tesseract-OCR for your system."
            )
        logging.info(f"Tesseract executable found at: {tesseract_path}")

        # pdf2image depends on Poppler
        pdftoppm_path = shutil.which('pdftoppm')
        if not pdftoppm_path:
            raise ImportError(
                "Poppler is not installed or not in your PATH. "
                "OCR2TXTTool depends on pdf2image, which requires Poppler. "
                "Please install poppler-utils (on Linux) or Poppler for your system."
            )
        logging.info(f"Poppler (pdftoppm) executable found at: {pdftoppm_path}")

    def forward(self, file_name: str, language: str = 'eng'):
        # --- Security: Sanitize and validate the file path ---
        full_path = os.path.abspath(os.path.join(self.safe_dir, os.path.basename(file_name)))

        if not full_path.startswith(self.safe_dir):
            return f"Error: Access denied. File '{file_name}' is outside the safe directory."

        if not os.path.exists(full_path):
            return f"Error: File not found at '{full_path}'."

        try:
            logging.info(f"Starting OCR process for '{full_path}' with language '{language}'.")
            # Convert PDF to a list of PIL images
            images = convert_from_path(full_path)

            full_text = []
            for i, image in enumerate(images):
                logging.info(f"  - Performing OCR on page {i + 1}/{len(images)}")
                # Use pytesseract to extract text from the image
                text = pytesseract.image_to_string(image, lang=language)
                full_text.append(text)

            logging.info(f"Successfully completed OCR for '{full_path}'.")
            # Join the text from all pages
            return "\n\n--- Page Break ---\n\n".join(full_text)

        except Exception as e:
            error_message = f"An error occurred during the OCR process: {str(e)}"
            logging.error(error_message)
            return f"Error: {error_message}"

class CSV2TUPTool(SafeOpenTool):
    name = "csv_2_tup_tool"
    description = """This is a tool that extracts a tuple from a CSV file.
                     If the file is not in a safe directory it raises an exception."""
    inputs = {
        "file_name": {
            "type": "string",
            "description": "The name of the file to be opened."
        }
    }
    # output_type = "tuple[list[str] | None, list[list[str]] | None]"
    output_type = "object"

    def __init__(self, safe_dir):
        super().__init__(safe_dir)
        # logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
        logging.info("Secure CSV2TUPTool initialized.")

    def forward(self, file_name):
        csv_file = super().forward(file_name, "rt",)
        # Iterate through all the pages and extract text
        tupla = []
        tupla = read_dynamic_csv(csv_file)
        csv_file.close()
        return tupla

class _TextProcessor:
    """
    Encapsulates text preprocessing. Accepts pre-loaded models for efficiency.
    """
    def __init__(self, nlp, stopwords, use_lemmatization=True):
        self.nlp = nlp
        self.stopwords = stopwords
        self.use_lemmatization = use_lemmatization
        self.stemmer = PorterStemmer() if not use_lemmatization else None
        self.method_name = "Lemmatization" if use_lemmatization else "Stemming"

    def process(self, text):
        """Process text using the configured normalization method."""
        if self.use_lemmatization:
            return self._lemmatize(text)
        return self._stem(text)

    def _lemmatize(self, text):
        """Normalizes text using spaCy for robust tokenization and lemmatization."""
        doc = self.nlp(text)
        return [token.lemma_.lower() for token in doc if token.is_alpha and not token.is_stop]

    def _stem(self, text):
        """Normalizes text using NLTK for tokenization and Porter stemming."""
        tokens = nltk.word_tokenize(text)
        return [self.stemmer.stem(word.lower()) for word in tokens
                if word.isalpha() and word.lower() not in self.stopwords]

class LCSAnalyzerTool(Tool):
    """
    A tool to analyze two texts and find their Longest Common Subsequence (LCS).
    It uses advanced text normalization (stemming or lemmatization) and a
    space-efficient algorithm (Hirschberg's algorithm) for the calculation.
    """
    name = "lcs_analyzer"
    description = (
        "Calculates the Longest Common Subsequence (LCS) of two input texts. "
        "It first normalizes the texts by converting them into a sequence of root words "
        "using either lemmatization or stemming. Then, it uses an efficient algorithm "
        "to find the longest sequence of words common to both texts."
    )
    inputs = {
        "text1": {"type": "string", "description": "The first text to be analyzed."},
        "text2": {"type": "string", "description": "The second text to be analyzed."},
        "use_lemmatization": {"type": "boolean", "description": "If True (default), uses lemmatization for text normalization. If False, uses stemming.", "nullable": True},
        "parallel": {"type": "boolean", "description": "If True (default), processes the two texts in parallel to speed up normalization.", "nullable": True},
        "return_sequence": {"type": "boolean", "description": "If True (default), returns the actual LCS sequence of words. If False, returns only its length.", "nullable": True}
    }
    output_type = "string"  # The output will be a JSON string.

    # Class-level variables to hold the loaded models, so they are loaded only once.
    _nlp_spacy = None
    _nltk_stopwords = None

    def __init__(self):
        super().__init__()
        # logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
        # Use the correct class name to check if models are loaded.
        if LCSAnalyzerTool._nlp_spacy is None:
            self._setup_dependencies()

    def _setup_dependencies(self):
        """Downloads and loads all required NLTK and spaCy models."""
        try:
            nltk.data.find('tokenizers/punkt')
            nltk.data.find('corpora/stopwords')
        except LookupError:
            logging.info("Downloading NLTK data (punkt, stopwords)...")
            nltk.download('punkt', quiet=True)
            nltk.download('stopwords', quiet=True)

        try:
            # Assign to the class variable directly.
            LCSAnalyzerTool._nlp_spacy = spacy.load("en_core_web_sm")
            logging.info("spaCy model 'en_core_web_sm' loaded.")
        except OSError:
            logging.info("spaCy model 'en_core_web_sm' not found. Downloading...")
            spacy.cli.download("en_core_web_sm")
            LCSAnalyzerTool._nlp_spacy = spacy.load("en_core_web_sm")

        LCSAnalyzerTool._nltk_stopwords = set(stopwords.words('english'))

    def _hirschberg_lcs(self, X, Y):
        """Hirschberg's algorithm: O(mn) time, O(min(m,n)) space."""
        def lcs_length_forward(X, Y):
            m, n = len(X), len(Y)
            curr = [0] * (n + 1)
            for i in range(1, m + 1):
                prev = curr[:]
                for j in range(1, n + 1):
                    if X[i-1] == Y[j-1]:
                        curr[j] = prev[j-1] + 1
                    else:
                        curr[j] = max(curr[j-1], prev[j])
            return curr

        def lcs_length_backward(X, Y):
            return lcs_length_forward(X[::-1], Y[::-1])[::-1]

        if not X or not Y:
            return 0, []
        if len(X) == 1:
            return (1, [X[0]]) if X[0] in Y else (0, [])

        mid = len(X) // 2
        left_lengths = lcs_length_forward(X[:mid], Y)
        right_lengths = lcs_length_backward(X[mid:], Y)
        partition = max(range(len(Y) + 1), key=lambda k: left_lengths[k] + right_lengths[k])
        left_len, left_seq = self._hirschberg_lcs(X[:mid], Y[:partition])
        right_len, right_seq = self._hirschberg_lcs(X[mid:], Y[partition:])
        return left_len + right_len, left_seq + right_seq

    def _calculate_lcs_length_optimized(self, seq1, seq2):
        """Space-optimized LCS length calculation: O(min(m,n)) space."""
        if len(seq1) > len(seq2):
            seq1, seq2 = seq2, seq1
        m, n = len(seq1), len(seq2)
        prev = [0] * (m + 1)
        for j in range(1, n + 1):
            curr = [0] * (m + 1)
            for i in range(1, m + 1):
                if seq1[i-1] == seq2[j-1]:
                    curr[i] = prev[i-1] + 1
                else:
                    curr[i] = max(curr[i-1], prev[i])
            prev = curr
        return prev[m]

    def _process_texts_parallel(self, texts, use_lemmatization):
        """Process multiple texts in parallel using multiprocessing."""
        if len(texts) < 2 or sum(len(t) for t in texts) < 10000:
            processor = _TextProcessor(LCSAnalyzerTool._nlp_spacy, LCSAnalyzerTool._nltk_stopwords, use_lemmatization)
            return [processor.process(text) for text in texts]

        try:
            # Use functools.partial to create a function with the 'use_lemmatization' argument fixed.
            worker_func = partial(_lcs_worker_process, use_lemmatization=use_lemmatization)
            with Pool(processes=min(len(texts), os.cpu_count() or 2)) as pool:
                results = pool.map(worker_func, texts)
            return results
        except Exception as e:
            logging.warning(f"Multiprocessing pool failed with error: {e}. Falling back to serial processing.")
            processor = _TextProcessor(LCSAnalyzerTool._nlp_spacy, LCSAnalyzerTool._nltk_stopwords, use_lemmatization)
            return [processor.process(text) for text in texts]

    def forward(self, text1: str, text2: str, use_lemmatization: bool = True, parallel: bool = True, return_sequence: bool = True) -> str:
        """Executes the LCS analysis."""
        # Process texts
        if parallel:
            words1, words2 = self._process_texts_parallel([text1, text2], use_lemmatization)
        else:
            processor = _TextProcessor(LCSAnalyzerTool._nlp_spacy, LCSAnalyzerTool._nltk_stopwords, use_lemmatization)
            words1 = processor.process(text1)
            words2 = processor.process(text2)

        # Calculate LCS
        if return_sequence:
            lcs_len, lsc_seq = self._hirschberg_lcs(words1, words2)
        else:
            lcs_len = self._calculate_lcs_length_optimized(words1, words2)
            lsc_seq = None

        results = {
            'normalization_method': "Lemmatization" if use_lemmatization else "Stemming",
            'text1_normalized_word_count': len(words1),
            'text2_normalized_word_count': len(words2),
            'lcs_length': lcs_len,
            'lcs_sequence': lsc_seq
        }

        return json.dumps(results, indent=2)

class ListBPFunctionsTool(Tool):
    name = "list_bulletproof_functions"
    description = """
    Lists all available standard optimization functions stored in the internal BULLETPROOF library.
    Use this to discover available test functions (like 'mogadish', 'schwefel', 'cross_in_tray')
    before running an optimizer.
    """
    inputs = {
        "verbose": {
            "type": "boolean",
            "description": "If True (default), returns details (bounds, global min, description). If False, returns only names.",
            "nullable": True
        }
    }
    output_type = "string"

    def __init__(self):
        super().__init__()
        # logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
        logging.info("ListBPFunctionTool initialized.")

    def forward(self, verbose: bool = True):
        # Access the global dictionary safely
        # This looks for the variable defined in your main script
        bp_dict = globals().get('BULLETPROOF_FUNCTIONS', {})

        if not bp_dict:
            return "Error: The BULLETPROOF_FUNCTIONS library is empty or could not be found in the global scope."

        if verbose is None:
            verbose = True

        report = ["📚 **AVAILABLE OPTIMIZATION FUNCTIONS** 📚\n"]

        for name, data in bp_dict.items():
            if not verbose:
                report.append(f"- {name}")
            else:
                # Extract Metadata
                bounds = data.get('bounds', 'Custom')
                gmin = data.get('global_min', 'Unknown')

                # Attempt to extract a docstring/summary from the code source
                # We look for the first comment line inside the code string
                code_snippet = data.get('code', '')
                description = "No description provided."
                for line in code_snippet.split('\n'):
                    stripped = line.strip()
                    if stripped.startswith('#') and 'def' not in stripped and 'import' not in stripped:
                        description = stripped.lstrip('# ').strip()
                    break  # Take the first comment as the description

                report.append(f"🔹 **{name}**")
                report.append(f"   Description: {description}")
                report.append(f"   Bounds: {bounds}")
                report.append(f"   Known Global Min: {gmin}")
                report.append("")

        return "\n".join(report)

class GetBPFunctionCodeTool(Tool):
    name = "get_bulletproof_function_code"
    description = """
    Retrieves the raw Python source code for a specific function from the BULLETPROOF library.
    Use this when you need to inspect the code, modify it (e.g., convert 'numpy' logic to 'mpmath'),
    or pass it to a tool that doesn't support automatic lookup.
    """
    inputs = {
        "function_name": {
            "type": "string",
            "description": "The name of the function to retrieve (e.g., 'mogadish', 'rastrigin')."
        }
    }
    output_type = "string"

    def __init__(self):
        super().__init__()
        # logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
        logging.info("GetBPFunctionCodeTool initialized.")

    def forward(self, function_name: str):
        bp_dict = globals().get('BULLETPROOF_FUNCTIONS', {})

        clean_name = function_name.strip().lower()

        if clean_name not in bp_dict:
            return f"Error: Function '{function_name}' not found in the library. Use 'list_bulletproof_functions' to see available options."

        data = bp_dict[clean_name]
        code = data.get('code', '')

        if not code:
            return f"Error: No source code found for '{function_name}'."

        return code

class SimAnnealTool(Tool):
    name = "simulated_annealing_optimizer"
    description = """
    Finds the global minimum using Simulated Annealing v2.
    Returns the solution and saves history to a CSV.

    STANDARD FUNCTIONS:
    You can simply pass the name of a standard function in 'function_code' (e.g., "ackley", "rastrigin", "rosenbrock").
    This will use pre-validated code and bounds.

    CUSTOM FUNCTIONS:
    Pass the full Python code definition: "def objective(x): return ...".

    CRITICAL:
    The CSV is saved in a secure area. The Plotter cannot read it directly.
    You must read the data using `csv_2_tup_tool` and INJECT the lists into the plotting code.
    """
    inputs = {
        "function_code": {
            "type": "string",
            "description": "Either the Python code defining 'def objective(x): ...' OR the name of a standard test function (e.g., 'rastrigin')."
        },
        "bounds": {
            "type": "object",
            "description": "List of tuples for min/max per dimension. Optional if using a standard function name."
        },
        "output_filename": {
            "type": "string",
            "description": "Filename for history CSV (e.g., 'run1.csv'). Ends in .csv."
        },
        "max_iterations": {
            "type": "integer",
            "description": "Max iterations. Defaults to 10000.",
            "nullable": True
        },
        "initial_temperature": {
            "type": "number",
            "description": "Starting temp. Defaults to 1000.0.",
            "nullable": True
        },
        "cooling_rate": {
            "type": "number",
            "description": "Cooling rate (0 < r < 1). Defaults to 0.95.",
            "nullable": True
        },
        "neighbor_type": {
            "type": "string",
            "description": "Strategy. Options: 'gaussian', 'uniform', 'jump'. Default: 'gaussian'.",
            "nullable": True
        },
        "schedule_type": {
            "type": "string",
            "description": "Schedule. Options: 'exponential', 'log', 'cauchy', 'adaptive'.",
            "nullable": True
        },
        "restart_stagnation": {
            "type": "integer",
            "description": "If provided, restarts/reheats after N iterations without improvement. (e.g., 500).",
            "nullable": True
        },
        "adapt_neighbor": {
            "type": "boolean",
            "description": "If True (default), automatically adjusts step size. If False, uses fixed scale.",
            "nullable": True
        }
    }
    output_type = "string"

    def __init__(self, safe_dir):
        super().__init__()
        self.safe_dir = safe_dir
        # logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
        logging.info("SimAnnealTool initialized (v0.6.0: Standard Library Support).")

    def forward(self, function_code: str, bounds, output_filename: str,
                max_iterations: int = 10000, initial_temperature: float = 1000.0,
                cooling_rate: float = 0.95, neighbor_type: str = "gaussian",
                schedule_type: str = "exponential", restart_stagnation: int = None,
                adapt_neighbor: bool = True):
        try:
            # 0. Secure File Path
            if not output_filename.lower().endswith('.csv'):
                return f"Error: The output_filename '{output_filename}' must end with .csv."

            csv_path = os.path.join(self.safe_dir, os.path.basename(output_filename))

            # ─────────────────────────────────────────────────────────────────
            # 1. FUNCTION SWITCHER LOGIC (New in v0.6.0)
            # ─────────────────────────────────────────────────────────────────
            clean_name = function_code.strip().lower()
            known_global_min = None
            is_predefined = False

            # Check if user passed a standard name
            if clean_name in BULLETPROOF_FUNCTIONS:
                logging.info(f"SimAnnealTool: Using standard function '{clean_name}'")
                data = BULLETPROOF_FUNCTIONS[clean_name]

                # Replace the name with the actual Python code
                function_code = data["code"].strip()
                known_global_min = data.get("global_min")
                is_predefined = True

                # Bounds Logic for Standard Functions:
                # Use User bounds if provided, otherwise fall back to Dictionary bounds
                if not bounds:
                    bounds_list = data["bounds"]
                else:
                    # User wants to override standard bounds
                    if isinstance(bounds, str):
                        try:
                            bounds_list = ast.literal_eval(bounds)
                        except Exception as e:
                            return f"Error parsing user override bounds: {e}"
                    else:
                        bounds_list = bounds
            else:
                # Custom Function Path (Legacy)
                if isinstance(bounds, str):
                    try:
                        bounds_list = ast.literal_eval(bounds)
                    except Exception as e:
                        return f"Error parsing bounds: {e}"
                else:
                    bounds_list = bounds

            # ─────────────────────────────────────────────────────────────────
            # 2. Neighbors & Schedule
            # ─────────────────────────────────────────────────────────────────
            n_map = {"gaussian": sa_neighbors.gaussian_neighbor, "uniform": sa_neighbors.uniform_neighbor, "jump": sa_neighbors.jump_neighbor}
            selected_neighbor = n_map.get(str(neighbor_type).lower(), sa_neighbors.gaussian_neighbor)

            valid_schedules = ["exponential", "log", "cauchy", "adaptive"]
            s_type = str(schedule_type).lower() if str(schedule_type).lower() in valid_schedules else "exponential"

            # 3. Function Compilation
            local_scope = {}
            # Allow common math libraries in exec scope
            global_scope = {'np': np, 'math': math, 'abs': abs, 'min': min, 'max': max, 'pow': pow}
            try:
                exec(function_code, global_scope, local_scope)
            except Exception as e:
                return f"Syntax error in function code: {e}"

            if 'objective' not in local_scope:
                return "Error: Function code must define 'def objective(x):'"

            raw_objective_fn = local_scope['objective']

            def objective_wrapper(x):
                if np.isscalar(x):
                    return raw_objective_fn(np.array([x]))
                return raw_objective_fn(x)

            # 4. Initialize SA
            do_adapt = True if adapt_neighbor is None else adapt_neighbor

            # Check if arguments exist in the loaded class to prevent TypeError if legacy lib is loaded
            init_args = {}
            import inspect
            sig = inspect.signature(SimulatedAnnealing.__init__)
            if 'restart_stagnation' in sig.parameters:
                init_args['restart_stagnation'] = restart_stagnation
                init_args['restart_mode'] = "reheat"
            if 'adapt_neighbor' in sig.parameters:
                init_args['adapt_neighbor'] = do_adapt

            sa = SimulatedAnnealing(
                objective_function=objective_wrapper,
                bounds=bounds_list,
                initial_temperature=initial_temperature,
                cooling_rate=cooling_rate,
                max_iterations=max_iterations,
                neighbor_fn=selected_neighbor,
                schedule_type=s_type,
                **init_args
            )
            # Smart history container: use deque if run will be huge
            use_deque = max_iterations > 50_000
            # deque when max_iterations > 50000
            if use_deque:
                # Keep only last 100k points + all best-improvement points
                history = deque(maxlen=100_000)
            else:
                history = []
            # 5. Optimize
            best_sol, best_val, history = sa.optimize()

            # 6. Write CSV (Robust to version mismatch)
            delimiter_char = globals().get('csv_field_delim', ';')

            # Determine dimensions from first record
            first_record = history[0]
            if len(first_record) >= 1:
                first_pos = first_record[0]
            else:
                return "Error: Optimization returned empty history."

            if np.isscalar(first_pos):
                x_columns = ['x']
            else:
                x_columns = [f'x{i}' for i in range(len(first_pos))]

            fieldnames = ['iteration', 'energy', 'best_so_far', 'accepted', 'temperature', 'neighbor_scale'] + x_columns

            with open(csv_path, mode='w', newline='') as f:
                writer = csv.DictWriter(f, fieldnames=fieldnames, delimiter=delimiter_char)
                writer.writeheader()

                for it, row_data in enumerate(history):
                    # Robust unpacking (Handle v1 vs v6 tuples)
                    if len(row_data) == 6:
                        pos, energy_val, best_val_hist, accepted_flag, temp, scale = row_data
                    elif len(row_data) == 2:
                        pos, energy_val = row_data
                        best_val_hist, accepted_flag, temp, scale = energy_val, 1, 0.0, 0.0
                    else:
                        continue

                    row = {
                        'iteration': it,
                        'energy': energy_val,
                        'best_so_far': best_val_hist,
                        'accepted': int(accepted_flag),
                        'temperature': temp,
                        'neighbor_scale': scale,
                    }
                    if np.isscalar(pos):
                        row['x'] = float(pos)
                    else:
                        for i, val in enumerate(pos):
                            row[f'x{i}'] = float(val)
                    writer.writerow(row)

            if isinstance(best_sol, np.ndarray):
                sol_list = best_sol.tolist()
            else:
                sol_list = best_sol

            # 7. Construct Result Message
            regret_msg = ""
            if known_global_min is not None:
                regret = abs(best_val - known_global_min)
                regret_msg = f"Known Global Min: {known_global_min}\nRegret (Error): {regret:.6e}\n"

            result_msg = (f"Optimization Successful.\n"
                          f"Function: {clean_name if is_predefined else 'Custom'}\n"
                          f"Global Minimum Found: {best_val}\n"
                          f"{regret_msg}"
                          f"At Coordinates: {sol_list}\n"
                          f"History saved to: {csv_path}\n"
                          f"Settings: Adapt={do_adapt}, Restart={restart_stagnation}\n\n"
                          f"*** PLOTTING INSTRUCTIONS ***\n"
                          f"1. Use `csv_2_tup_tool('{output_filename}')`.\n"
                          f"2. Delimiter is '{delimiter_char}'.\n"
                          f"3. INJECT lists into python_plotter code using f-strings.\n"
                          f"   Example:\n"
                          f"   ```python\n"
                          f"   header, rows = csv_2_tup_tool('{output_filename}')\n"
                          f"   # Col 0=Iter, 1=Energy, 2=Best, 4=Temp\n"
                          f"   x = [float(r[0]) for r in rows]\n"
                          f"   y = [float(r[1]) for r in rows]\n"
                          f"   plot_code = f'''\n"
                          f"   plt.plot({{x}}, {{y}})\n"
                          f"   '''\n"
                          f"   python_plotter(plot_code, 'out.png')\n"
                          f"   ```")

            print(result_msg)
            return result_msg

        except Exception as e:
            logging.exception("Error in SimAnnealTool")
            return f"An error occurred: {str(e)}"

class SAAnalysisTool(Tool):
    name = "sa_analysis_tool"
    description = """
    Advanced analysis of Simulated Annealing history CSV.
    Detects convergence issues, acceptance problems, stagnation patterns,
    and gives precise, actionable tuning recommendations (v3 — fully upgraded).
    Supports all v2+ features: adaptive scaling, restarts, temperature logging.
    """
    inputs = {
        "csv_filename": {
            "type": "string",
            "description": "Name of the history CSV file (e.g., 'run1.csv')"
        }
    }
    output_type = "string"

    def __init__(self, safe_dir):
        super().__init__()
        self.safe_dir = safe_dir
        # logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
        logging.info("SAAnalysisTool initialized.")

    def forward(self, csv_filename: str):
        if not csv_filename.lower().endswith('.csv'):
            return "Error: File must end with .csv"

        path = os.path.join(self.safe_dir, os.path.basename(csv_filename))
        if not os.path.exists(path):
            return f"Error: File not found: {path}"

        try:
            with open(path, 'r') as f:
                reader = csv.DictReader(f, delimiter=';')
                rows = list(reader)

            if len(rows) < 50:
                return "Not enough data for meaningful analysis (<50 iterations)."

            # Parse required columns
            iters = np.array([int(r['iteration']) for r in rows])
            energy = np.array([float(r['energy']) for r in rows])
            best_energy = np.array([float(r['best_so_far']) for r in rows])  # recommended to log
            accepted = np.array([int(r.get('accepted', 1)) for r in rows])  # fallback 1
            temperature = np.array([float(r.get('temperature', 1.0)) for r in rows])
            scale = np.array([float(r.get('neighbor_scale', 0.1)) for r in rows])

            n = len(iters)
            final_best = best_energy[-1]
            best_idx = np.argmin(best_energy)
            conv_pct = best_idx / n * 100

            report = [
                "SIMULATED ANNEALING ANALYSIS REPORT (v3)",
                "="*60,
                f"Total iterations       : {n:,}",
                f"Final best energy      : {final_best:.10f}",
                f"Best found at iter     : {best_idx} ({conv_pct:.1f}% of run)",
                f"Initial temperature    : {temperature[0]:.2f}",
                f"Final temperature      : {temperature[-1]:.2e}",
                f"Final neighbor scale   : {scale[-1]:.2e}",
                "",
            ]

            # 1. Acceptance Rate Analysis
            accept_rate = accepted.mean() * 100
            late_accept = accepted[-max(100, n//10):].mean() * 100
            report += [
                "ACCEPTANCE RATE",
                "-"*30,
                f"Overall acceptance     : {accept_rate:.1f}%",
                f"Late-phase acceptance  : {late_accept:.1f}%",
            ]
            if accept_rate < 15:
                report += ["Too low! Steps too small or temperature too low early."]
                report += ["→ Enable or keep adapt_neighbor=True"]
                report += ["→ Try higher initial_temperature"]
            elif accept_rate > 70:
                report += ["Too high! Too random, wasting evaluations."]
                report += ["→ Lower initial_temperature"]
                report += ["→ Use faster cooling (e.g. cooling_rate=0.90)"]
            else:
                report += ["Healthy range (15–70%). Good exploration/exploitation balance."]

            # 2. Convergence & Quenching
            report += ["", "CONVERGENCE BEHAVIOR", "-"*30]
            if conv_pct < 8:
                report += ["QUENCHING: Best found too early → cooled too fast!"]
                report += ["→ Use slower schedule: 'log', 'cauchy', or cooling_rate ≥ 0.99"]
                report += ["→ Or enable 'adaptive' schedule"]
            elif conv_pct > 90:
                report += ["SLOW CONVERGENCE: Still improving at the end."]
                report += ["→ Increase max_iterations by 50–100%"]
            else:
                report += ["Convergence timing looks good."]

            # 3. Stagnation & Restart Analysis
            report += ["", "STAGNATION & RESTART NEEDS", "-"*30]
            stagnant_periods = []
            current_stag = 0
            for i in range(1, n):
                if best_energy[i] >= best_energy[i-1]:
                    current_stag += 1
                else:
                    if current_stag > 200:
                        stagnant_periods.append((i - current_stag, current_stag))
                    current_stag = 0
            if current_stag > 200:
                stagnant_periods.append((n - current_stag, current_stag))

            if stagnant_periods:
                longest = max(stagnant_periods, key=lambda x: x[1])
                report += [f"Detected {len(stagnant_periods)} stagnation period(s)"]
                report += [f"Longest: {longest[1]} iterations (from {longest[0]})"]
                suggested = max(300, longest[1] // 2)
                report += [f"STRONG RECOMMENDATION: Enable restart_stagnation = {suggested}"]
                report += ["Best modes: 'reheat' (safe), 'random_jump' (aggressive)"]
            else:
                report += ["No major stagnation — excellent run!"]

            # 4. Adaptive Scaling Effectiveness
            if np.std(scale) > 1e-8:  # scale actually changed
                report += ["", "ADAPTIVE SCALING", "-"*30]
                if 0.3 < late_accept < 0.6:
                    report += ["Adaptive scaling worked perfectly!"]
                    report += [f"Final scale {scale[-1]:.2e} is a good starting point for future runs."]
                else:
                    report += ["Adaptive scaling tried but didn't converge to ideal rate."]
                    report += ["→ Try larger adapt_window (e.g. 200) or keep running longer."]
            else:
                report += ["Adaptive scaling was disabled."]

            # 5. Final Recommendations Summary
            report += ["", "ACTION PLAN", "="*60]
            recs = []
            if 'QUENCHING' in "".join(report):
                recs += ["Use schedule_type='log' or cooling_rate=0.995+"]
            if stagnant_periods:
                recs += [f"Set restart_stagnation={max(300, longest[1]//2)}"]
            if accept_rate > 70:
                recs += ["Lower initial_temperature by 50%"]
            if n < 20000 and conv_pct > 80:
                recs += ["Increase max_iterations to 30k–50k"]
            if not recs:
                recs = ["No major issues! This was a strong run. Consider minor scaling up."]

            report += recs
            report += ["", "Tip: Rerun with these changes and compare best energy!"]

            return "\n".join(report)

        except Exception as e:
            logging.exception("SAAnalysisTool failed")
            return f"Analysis failed: {str(e)}"

class GATool(Tool):
    name = "genetic_algorithm_optimizer"
    description = """
    Finds the global minimum using a Real-Coded Genetic Algorithm.
    Useful for multimodal functions where Simulated Annealing might get stuck.

    OUTPUT:
    - Returns best solution.
    - Saves history to CSV (Generation, Best Energy, Diversity).

    CRITICAL:
    Read CSV using `csv_2_tup_tool` and INJECT data into `python_plotter`.
    """
    inputs = {
        "function_code": {
            "type": "string",
            "description": "Python code 'def objective(x): ...' OR a standard function name (e.g., 'rastrigin', 'schwefel')."
        },
        "bounds": {
            "type": "object",
            "description": "Bounds e.g. [(-5, 5)]. Optional if using a standard function name."
        },
        "output_filename": {
            "type": "string",
            "description": "CSV filename."
        },
        "pop_size": {"type": "integer", "description": "Population size (default 50).", "nullable": True},
        "generations": {"type": "integer", "description": "Max generations (default 100).", "nullable": True},
        "mutation_rate": {"type": "number", "description": "Prob of mutation (0.0-1.0).", "nullable": True},
        "crossover_rate": {"type": "number", "description": "Prob of crossover (0.0-1.0).", "nullable": True}
    }
    output_type = "string"

    def __init__(self, safe_dir):
        super().__init__()
        self.safe_dir = safe_dir
        # logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
        logging.info("GATool initialized (v0.1.0 with Dictionary Lookup).")

    def forward(self, function_code, bounds, output_filename,
                pop_size=50, generations=100, mutation_rate=0.1,
                crossover_rate=0.8):

        # 0. Secure Path
        if not output_filename.lower().endswith('.csv'):
            return f"Error: The output_filename '{output_filename}' must end with .csv."
        csv_path = os.path.join(self.safe_dir, os.path.basename(output_filename))

        # ─────────────────────────────────────────────────────────────────
        # 1. FUNCTION SWITCHER LOGIC
        # ─────────────────────────────────────────────────────────────────
        # Retrieve the dictionary from the global scope (defined in main script)
        bulletproof_dict = globals().get('BULLETPROOF_FUNCTIONS', {})

        clean_name = function_code.strip().lower()
        known_global_min = None
        code_to_compile = ""
        bounds_list = []

        if clean_name in bulletproof_dict:
            logging.info(f"GATool: Using standard function '{clean_name}'")
            data = bulletproof_dict[clean_name]

            # 1. Get Code
            code_to_compile = data["code"].strip()
            # 2. Get Known Min (for reporting)
            known_global_min = data.get("global_min")

            # 3. Handle Bounds (User Override vs Default)
            if not bounds:
                bounds_list = data["bounds"]
            else:
                if isinstance(bounds, str):
                    try:
                        bounds_list = ast.literal_eval(bounds)
                    except Exception as e:
                        return f"Error parsing user override bounds: {e}"
                else:
                    bounds_list = bounds
        else:
            # Custom Code Mode
            code_to_compile = function_code
            if not bounds:
                return "Error: You must provide 'bounds' for custom functions."
            if isinstance(bounds, str):
                try:
                    bounds_list = ast.literal_eval(bounds)
                except Exception as e:
                    return f"Error parsing bounds: {e}"
            else:
                bounds_list = bounds

        # ─────────────────────────────────────────────────────────────────
        # 2. COMPILATION (Turn String into Callable Function)
        # ─────────────────────────────────────────────────────────────────
        local_scope = {}
        global_scope = {'np': np, 'math': math}
        try:
            exec(code_to_compile, global_scope, local_scope)
        except Exception as e:
            return f"Syntax Error in function code: {e}"

        if 'objective' not in local_scope:
            return "Error: The code must define a function named 'objective(x)'."

        raw_fn = local_scope['objective']

        # Wrapper to handle 1D scalars vs Arrays
        def wrapper(x):
            if np.isscalar(x):
                return raw_fn(np.array([x]))
            return raw_fn(x)

        # ─────────────────────────────────────────────────────────────────
        # 3. RUN OPTIMIZATION
        # ─────────────────────────────────────────────────────────────────
        try:
            ga = RealGeneticAlgorithm(
                objective_function=wrapper,  # Pass the compiled function object!
                bounds=bounds_list,
                pop_size=pop_size or 50,
                max_generations=generations or 100,
                mutation_rate=mutation_rate or 0.1,
                crossover_rate=crossover_rate or 0.8
            )

            best_sol, best_val, history = ga.optimize()
        except Exception as e:
            logging.exception("GATool Runtime Error")
            return f"Error during GA execution: {str(e)}"

        # ─────────────────────────────────────────────────────────────────
        # 4. WRITE CSV
        # ─────────────────────────────────────────────────────────────────
        delim = globals().get('csv_field_delim', ';')

        # Determine dimension for headers based on the first solution in history
        first_sol = history[0]['best_solution_x']
        dims = 1 if np.isscalar(first_sol) else len(first_sol)
        x_cols = [f'x{i}' for i in range(dims)]

        try:
            with open(csv_path, 'w', newline='') as f:
                headers = ['generation', 'best_energy', 'avg_energy', 'diversity'] + x_cols
                writer = csv.DictWriter(f, fieldnames=headers, delimiter=delim)
                writer.writeheader()

                for row in history:
                    csv_row = {
                        'generation': row['generation'],
                        'best_energy': row['best_energy'],
                        'avg_energy': row['avg_energy'],
                        'diversity': row['diversity']
                    }
                    # Unpack solution
                    sol = row['best_solution_x']
                    if np.isscalar(sol):
                        csv_row['x0'] = float(sol)
                    else:
                        for i, v in enumerate(sol):
                            csv_row[f'x{i}'] = float(v)
                    writer.writerow(csv_row)
        except Exception as e:
            return f"Error writing CSV: {e}"

        if isinstance(best_sol, np.ndarray):
            best_sol = best_sol.tolist()

        # ─────────────────────────────────────────────────────────────────
        # 5. REPORTING
        # ─────────────────────────────────────────────────────────────────
        # Compare with known global minimum if available
        comparison_msg = ""
        if known_global_min is not None:
            diff = abs(best_val - known_global_min)
            if diff < 1e-4:
                comparison_msg = f"\n✅ SUCCESS: Hit Global Minimum (Diff: {diff:.2e})"
            else:
                comparison_msg = f"\n⚠️ GAP: {diff:.4f} away from Global Minimum ({known_global_min})"

        return (f"GA Optimization Complete.\n"
                f"Global Min Found: {best_val}\n"
                f"At Coordinates: {best_sol}"
                f"{comparison_msg}\n"
                f"History saved to {csv_path}\n\n"
                f"**PLOT INSTRUCTIONS**:\n"
                f"Plot 'best_energy' vs 'generation' for convergence.\n"
                f"Plot 'diversity' vs 'generation' to see if population collapsed.")

class GAAnalysisTool(Tool):
    name = "ga_analysis_tool"
    description = """
    Analyzes 'history.csv' from the Genetic Algorithm.
    Diagnoses 'Premature Convergence' by looking at Population Diversity vs Energy.
    """
    inputs = {
        "csv_filename": {
            "type": "string",
            "description": "Name of the history CSV file."
        }
    }
    output_type = "string"

    def __init__(self, safe_dir):
        super().__init__()
        self.safe_dir = safe_dir
        # logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
        logging.info("GAAnalysisTool initialized.")

    def forward(self, csv_filename: str):
        if not csv_filename.lower().endswith('.csv'):
            return "Error: .csv required"
        path = os.path.join(self.safe_dir, os.path.basename(csv_filename))
        if not os.path.exists(path):
            return "Error: File not found"

        try:
            delim = globals().get('csv_field_delim', ';')
            with open(path, 'r') as f:
                reader = csv.DictReader(f, delimiter=delim)
                rows = list(reader)

            if not rows:
                return "Empty file."

            # Parse columns
            gens = np.array([int(r['generation']) for r in rows])
            best_E = np.array([float(r['best_energy']) for r in rows])
            avg_E = np.array([float(r['avg_energy']) for r in rows])
            diversity = np.array([float(r['diversity']) for r in rows])

            n_gens = len(gens)
            final_best = best_E[-1]

            # 1. Identify Convergence Generation (When Diversity drops near zero)
            # Threshold: 1% of initial diversity
            initial_div = diversity[0] if diversity[0] > 0 else 1.0
            conv_threshold = initial_div * 0.01

            # Find first index where diversity < threshold
            conv_indices = np.where(diversity < conv_threshold)[0]
            if len(conv_indices) > 0:
                conv_gen = gens[conv_indices[0]]
                conv_pct = (conv_gen / n_gens) * 100
                is_converged = True
            else:
                conv_gen = n_gens
                conv_pct = 100
                is_converged = False

            # 2. Selection Pressure Analysis
            # If Avg Energy drops much slower than Best Energy, the selection pressure is low.
            # If Avg Energy hugs Best Energy tightly, selection pressure is high (Elitism).
            energy_gap = avg_E - best_E
            avg_gap = np.mean(energy_gap)

            report = [
                "GENETIC ALGORITHM REPORT",
                "="*40,
                f"Generations: {n_gens}",
                f"Final Best Energy: {final_best:.6f}",
                f"Initial Diversity: {initial_div:.4f}",
                f"Final Diversity: {diversity[-1]:.4e}",
                "-"*30,
                "DIAGNOSIS:"
            ]

            # Heuristics
            if is_converged:
                report += [f"✅ CONVERGED: Population collapsed at Gen {conv_gen} ({conv_pct:.1f}%)."]
                if conv_pct < 20:
                    report += ["⚠️ PREMATURE CONVERGENCE: Diversity lost too quickly."]
                    report += ["   -> HINT: Increase 'mutation_rate' or 'pop_size'."]
                else:
                    report += ["   -> Timing looks healthy."]
            else:
                report += ["⚠️ NOT CONVERGED: Population is still diverse."]
                report += ["   -> HINT: Increase 'generations' or 'crossover_rate'."]

            if avg_gap < (initial_div * 0.1):
                report += ["ℹ️ HIGH SELECTIVE PRESSURE: The whole population followed the leader."]
            else:
                report += ["ℹ️ HIGH VARIANCE: Many poor individuals survive (High mutation?)."]

            return "\n".join(report)

        except Exception as e:
            return f"Analysis Error: {e}"

class BOToolGv1_v3_2_0(Tool):
    name = "bayesian_optimizer"
    description = """
    Finds the global minimum using Bayesian Optimization (Gaussian Processes).
    Best for EXPENSIVE functions where you can only afford a few iterations (e.g. < 50).

    OUTPUT:
    - Returns best solution found.
    - Saves history to CSV.

    CRITICAL:
    - Uses `bayesian-optimization` package (v3.2.0+ compatible).
    - Read CSV using `csv_2_tup_tool` and INJECT data into `python_plotter`.
    """
    inputs = {
        "function_code": {
            "type": "string",
            "description": "Python code 'def objective(x): ...' OR a standard function name (e.g., 'rastrigin', 'schwefel')."
        },
        "bounds": {
            "type": "object",
            "description": "List of tuples e.g. [(-5, 5)]. Optional if using a standard function name."
        },
        "output_filename": {
            "type": "string",
            "description": "Filename for history CSV (e.g., 'bo_run1.csv'). Ends in .csv."
        },
        "n_iter": {
            "type": "integer",
            "description": "Total optimization steps (after init). Default 20.",
            "nullable": True
        },
        "init_points": {
            "type": "integer",
            "description": "Number of random exploration steps before model starts. Default 5.",
            "nullable": True
        },
        "acq_type": {
            "type": "string",
            "description": "Acquisition: 'ucb' (Upper Confidence Bound), 'ei' (Expected Improvement), or 'poi' (Probability Of Improvement). Default 'ucb'.",
            "nullable": True
        },
        "kappa": {
            "type": "number",
            "description": "Exploration weight for UCB. Higher (e.g. 5.0)=Explore; Lower (e.g. 1.0)=Exploit. Default 2.5.",
            "nullable": True
        },
        "xi": {
            "type": "number",
            "description": "Exploration weight for EI. Default 0.0.",
            "nullable": True
        }
    }
    output_type = "string"

    def __init__(self, safe_dir):
        super().__init__()
        self.safe_dir = safe_dir
        logging.info("BOTool initialized (v0.6.2 updated strictly for BO v3.2.0 constructor signature).")

    def forward(self, function_code: str, bounds, output_filename: str,
                n_iter: int = 20, init_points: int = 5,
                acq_type: str = 'ucb', kappa: float = 2.5, xi: float = 0.0):

        try:
            # 2. Secure File Path
            if not output_filename.lower().endswith('.csv'):
                return f"Error: The output_filename '{output_filename}' must end with .csv."
            csv_path = os.path.join(self.safe_dir, os.path.basename(output_filename))

            # ─────────────────────────────────────────────────────────────────
            # 3. FUNCTION SWITCHER LOGIC
            # ─────────────────────────────────────────────────────────────────
            bulletproof_dict = globals().get('BULLETPROOF_FUNCTIONS', {})
            clean_name = function_code.strip().lower()

            code_to_compile = ""
            bounds_list = []
            known_global_min = None

            if clean_name in bulletproof_dict:
                logging.info(f"BOTool: Using standard function '{clean_name}'")
                data = bulletproof_dict[clean_name]

                # 1. Get Code & Known Min
                code_to_compile = data["code"].strip()
                known_global_min = data.get("global_min")

                # 2. Handle Bounds
                if not bounds:
                    bounds_list = data["bounds"]
                else:
                    if isinstance(bounds, str):
                        try:
                            bounds_list = ast.literal_eval(bounds)
                        except Exception as e:
                            return f"Error parsing user override bounds: {e}"
                    else:
                        bounds_list = bounds
            else:
                # Custom Code Mode
                code_to_compile = function_code
                if not bounds:
                    return "Error: You must provide 'bounds' for custom functions."
                if isinstance(bounds, str):
                    try:
                        bounds_list = ast.literal_eval(bounds)
                    except Exception as e:
                        return f"Error parsing bounds: {e}"
                else:
                    bounds_list = bounds

            # ─────────────────────────────────────────────────────────────────
            # 4. COMPILATION
            # ─────────────────────────────────────────────────────────────────
            local_scope = {}
            global_scope = {'np': np, 'math': math, 'abs': abs, 'min': min, 'max': max, 'pow': pow}

            try:
                exec(code_to_compile, global_scope, local_scope)
            except Exception as e:
                return f"Syntax error in function code: {e}"

            if 'objective' not in local_scope:
                return "Error: Function 'objective(x)' not found in code."

            raw_objective_fn = local_scope['objective']

            # 5. Wrapper: Minimize <-> Maximize translation
            def bo_wrapper(**kwargs):
                # Ensure correct argument order (x0, x1, x2...)
                sorted_keys = sorted(kwargs.keys())
                x_vec = np.array([kwargs[k] for k in sorted_keys])
                val = raw_objective_fn(x_vec)
                return -float(val)

            # 6. Setup BO Parameters
            pbounds = {f'x{i}': b for i, b in enumerate(bounds_list)}

            n_iter = 20 if n_iter is None else n_iter
            init_points = 5 if init_points is None else init_points
            acq = acq_type.lower() if acq_type else 'ucb'
            k_val = 2.5 if kappa is None else kappa
            xi_val = 0.0 if xi is None else xi

            # Construct the AcquisitionFunction instance
            if acq == 'ei':
                utility = ExpectedImprovement(xi=xi_val)
            elif acq == 'poi':
                utility = ProbabilityOfImprovement(xi=xi_val)
            else:
                utility = UpperConfidenceBound(kappa=k_val)

            # 7. Instantiate Optimizer (In v3.2.0 acquisition_function belongs here)
            optimizer = BayesianOptimization(
                f=bo_wrapper,
                pbounds=pbounds,
                random_state=1,
                verbose=0,
                allow_duplicate_points=True,
                acquisition_function=utility
            )

            # 8. Run Optimization
            logging.info(f"BO Start: {acq}, n_iter={n_iter}, init={init_points}")

            # Maximize method is strictly limited to init_points and n_iter
            optimizer.maximize(
                init_points=init_points,
                n_iter=n_iter
            )

            # 9. Extract Results & Write CSV
            best_res = optimizer.max
            best_val_minimized = -best_res['target']  # Invert back

            best_params = [best_res['params'][f'x{i}'] for i in range(len(bounds_list))]

            delimiter_char = globals().get('csv_field_delim', ';')
            history = optimizer.res
            dim_keys = [f'x{i}' for i in range(len(bounds_list))]
            current_best = np.inf

            with open(csv_path, mode='w', newline='') as f:
                fieldnames = ['iteration', 'energy', 'best_so_far'] + dim_keys
                writer = csv.DictWriter(f, fieldnames=fieldnames, delimiter=delimiter_char)
                writer.writeheader()

                for i, res in enumerate(history):
                    energy = -res['target']  # Invert back
                    if energy < current_best:
                        current_best = energy

                    row = {
                        'iteration': i,
                        'energy': energy,
                        'best_so_far': current_best
                    }
                    for k in dim_keys:
                        row[k] = res['params'][k]
                    writer.writerow(row)

            # 10. Reporting
            comparison_msg = ""
            if known_global_min is not None:
                diff = abs(best_val_minimized - known_global_min)
                if diff < 1e-3:
                    comparison_msg = f"\n✅ SUCCESS: Hit Global Minimum (Diff: {diff:.2e})"
                else:
                    comparison_msg = f"\n⚠️ GAP: {diff:.4f} away from Global Minimum ({known_global_min})"

            return (f"Bayesian Optimization Complete.\n"
                    f"Global Minimum: {best_val_minimized}\n"
                    f"At Coordinates: {best_params}"
                    f"{comparison_msg}\n"
                    f"History saved to: {csv_path}\n\n"
                    f"*** PLOTTING INSTRUCTIONS ***\n"
                    f"1. Use `csv_2_tup_tool('{output_filename}')`.\n"
                    f"2. Delimiter is '{delimiter_char}'.\n"
                    f"3. INJECT data into `python_plotter` using f-strings.\n"
                    f"   Example:\n"
                    f"   ```python\n"
                    f"   header, rows = csv_2_tup_tool('{output_filename}')\n"
                    f"   iters = [float(r[0]) for r in rows]\n"
                    f"   energy = [float(r[1]) for r in rows]\n"
                    f"   best = [float(r[2]) for r in rows]\n"
                    f"   plot_code = f'''\n"
                    f"   plt.plot({{iters}}, {{energy}}, 'bo', alpha=0.5, label='Sampled')\n"
                    f"   plt.plot({{iters}}, {{best}}, 'r-', linewidth=2, label='Best So Far')\n"
                    f"   '''\n"
                    f"   python_plotter(plot_code, 'bo_plot.png')\n"
                    f"   ```")

        except Exception as e:
            logging.exception("Error in BOTool")
            return f"An error occurred: {str(e)}"

class BOAnalysisTool(Tool):
    name = "bo_analysis_tool"
    description = """
    Analyzes 'optimization_history.csv' from Bayesian Optimization.
    Diagnoses Exploration (Variance) vs Exploitation (Convergence).
    """
    inputs = {
        "csv_filename": {
            "type": "string",
            "description": "Name of the history CSV file."
        }
    }
    output_type = "string"

    def __init__(self, safe_dir):
        super().__init__()
        self.safe_dir = safe_dir
        # logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
        logging.info("bo_analysis_tool initialized.")

    def forward(self, csv_filename: str):
        if not csv_filename.lower().endswith('.csv'):
            return "Error: .csv required"
        path = os.path.join(self.safe_dir, os.path.basename(csv_filename))
        if not os.path.exists(path):
            return "Error: File not found"

        try:
            delim = globals().get('csv_field_delim', ';')
            with open(path, 'r') as f:
                reader = csv.DictReader(f, delimiter=delim)
                rows = list(reader)

            if not rows:
                return "Empty file."

            energies = np.array([float(r['energy']) for r in rows])
            n = len(energies)

            # Extract positions
            x_keys = [k for k in rows[0].keys() if k.startswith('x')]
            positions = []
            for r in rows:
                positions.append([float(r[k]) for k in x_keys])
            positions = np.array(positions)

            best_idx = np.argmin(energies)
            best_val = energies[best_idx]

            # Metric 1: Exploration Radius (Standard Deviation of sampled points)
            pos_std = np.mean(np.std(positions, axis=0))

            # Metric 2: Convergence
            mid_idx = n // 2
            best_at_mid = np.min(energies[:mid_idx]) if mid_idx > 0 else energies[0]
            improvement_late = best_at_mid - best_val

            report = [
                "BAYESIAN OPTIMIZATION REPORT",
                "="*40,
                f"Total Samples: {n}",
                f"Best Energy: {best_val:.6f}",
                f"Exploration (Avg StdDev): {pos_std:.4f}",
                "-"*30,
                "DIAGNOSIS:"
            ]

            # Heuristics
            if pos_std < 0.5:
                report += ["⚠️ LOW EXPLORATION: Points clustered tightly."]
                report += ["   -> HINT: Increase 'kappa' (e.g. 5.0) or 'init_points'."]
            else:
                report += ["✅ GOOD EXPLORATION: Algorithm searched wide area."]

            if improvement_late <= 0 and n > 10:
                report += ["⚠️ STALLED: No improvement in second half."]
                report += ["   -> HINT: You might be exploiting too much. Switch to 'simulated_annealing' to fine-tune."]
            else:
                report += [f"✅ LEARNING: Improved by {improvement_late:.4f} in later stages."]

            return "\n".join(report)

        except Exception as e:
            return f"Analysis Error: {e}"

def read_dynamic_csv(csvfile) -> tuple[list[str] | None, list[list[str]] | None]:
    """
    Reads a CSV file into memory using the global 'csv_field_delim'.
    """
    header = None
    data_rows = []

    try:
        # Access the global delimiter
        delimiter_char = globals().get('csv_field_delim', ';')  # Default to ';' if not set

        # Create a CSV reader object using the global delimiter
        csv_reader = csv.reader(csvfile, delimiter=delimiter_char)

        # Read the header row
        try:
            header = next(csv_reader)
        except StopIteration:
            print(f"Warning: File is empty: {csvfile}")
            return [], []

        # Read the rest of the rows (data)
        for row in csv_reader:
            data_rows.append(row)

        return header, data_rows

    except FileNotFoundError as e:
        print(f"Error: File object not found/valid: {e}")
        return None, None
    except Exception as e:
        print(f"An error occurred while reading CSV: {e}")
        return None, None

def _lcs_worker_process(text, use_lemmatization):
    """
    Worker function that processes a single text.
    It creates a processor that uses the models loaded in the main process.
    """
    processor = _TextProcessor(
        nlp=LCSAnalyzerTool._nlp_spacy,
        stopwords=LCSAnalyzerTool._nltk_stopwords,
        use_lemmatization=use_lemmatization
    )
    return processor.process(text)
